pre_commit_task:
  name: Run pre-commit checks
  container:
    image: carterjones/ci-runner:latest
  script: pre-commit run --all

macos_task:
  name: Integration Test (MacOS)
  osx_instance:
    image: catalina-xcode-12.0
  test_script:
    - ./ci/integration-tests.sh

arch_task:
  name: Integration Test (Arch)
  allow_failures: true
  container:
    image: carterjones/arch
  test_script:
    - ./ci/prepare-container.sh
    - ./ci/integration-tests.sh

manjaro_task:
  name: Integration Test (Manjaro)
  allow_failures: true
  container:
    image: carterjones/manjaro
  test_script:
    - ./ci/prepare-container.sh
    - ./ci/integration-tests.sh

centos_8_task:
  name: Integration Test (CentOS 8)
  container:
    image: carterjones/centos-8
  test_script:
    - ./ci/prepare-container.sh
    - ./ci/integration-tests.sh

ubuntu_2004_task:
  name: Integration Test (Ubuntu 20.04)
  container:
    image: carterjones/ubuntu-20.04
  test_script:
    - ./ci/prepare-container.sh
    - ./ci/integration-tests.sh
