lint_task:
  name: Lint
  container:
    image: koalaman/shellcheck-alpine
  lint_script: ./ci/lint.sh

macos_task:
  name: Integration Test (MacOS)
  osx_instance:
    image: catalina-xcode-12.0
  test_script: ./install

arch_task:
  name: Integration Test (Arch)
  allow_failures: true
  container:
    image: carterjones/arch
  test_script: ./ci/integration-tests.sh

manjaro_task:
  name: Integration Test (Manjaro)
  allow_failures: true
  container:
    image: carterjones/manjaro
  test_script: ./ci/integration-tests.sh

centos_8_task:
  name: Integration Test (CentOS 8)
  container:
    image: carterjones/centos-8
  test_script: ./ci/integration-tests.sh

ubuntu_1804_task:
  name: Integration Test (Ubuntu 18.04)
  container:
    image: carterjones/ubuntu-18.04
  test_script: ./ci/integration-tests.sh

ubuntu_2004_task:
  name: Integration Test (Ubuntu 20.04)
  container:
    image: carterjones/ubuntu-20.04
  test_script: ./ci/integration-tests.sh
