sudo: required

services:
  - docker

jobs:
  include:
    - stage: tests
      script: docker run -v $(pwd):/nix-config carterjones/arch /bin/bash -c "cd /nix-config && ./install"
      env: OS=Arch
    - stage: tests
      script: docker run -v $(pwd):/nix-config carterjones/manjaro /bin/bash -c "cd /nix-config && ./install"
      env: OS=Manjaro
    - stage: tests
      script: docker run -v $(pwd):/nix-config carterjones/ubuntu-14.04 /bin/bash -c "cd /nix-config && ./install"
      env: OS=Ubuntu 14.04
    - stage: tests
      script: docker run -v $(pwd):/nix-config carterjones/ubuntu-16.04 /bin/bash -c "cd /nix-config && ./install"
      env: OS=Ubuntu 16.04
    - stage: tests
      script: docker run -v $(pwd):/nix-config carterjones/ubuntu-18.04 /bin/bash -c "cd /nix-config && ./install"
      env: OS=Ubuntu 18.04
