language: bash
dist: bionic
os: linux

jobs:
  include:
    - stage: lint
      script: ./ci/lint.sh
    - stage: test
      env: OS=arch
      script: ./ci/test.sh
    - stage: test
      env: OS=manjaro
      script: ./ci/test.sh
    - stage: test
      env: OS=ubuntu-18.04
      script: ./ci/test.sh
    - stage: test
      env: OS=ubuntu-20.04
      script: ./ci/test.sh
    - stage: test
      env: OS=centos-8
      script: ./ci/test.sh
    - stage: test
      env: OS=macos
      os: osx
      osx_image: xcode11.3
      script: ./ci/test.sh
