language: bash

os:
  - linux
  - osx

sudo: required

matrix:
  allow_failures:
    - env: OS=Arch
    - env: OS=Manjaro
  exclude:
    - os: osx
      env: TASK=Shellcheck
    - os: osx
      env: OS=Arch
    - os: osx
      env: OS=Manjaro
    - os: osx
      env: OS=Ubuntu_16.04
    - os: osx
      env: OS=Ubuntu_18.04
    - os: osx
      env: OS=CentOS_7
    - os: linux
      env: OS=Mac_OS_X

env:
  - TASK=Shellcheck
  - OS=Arch
  - OS=Manjaro
  - OS=Ubuntu_16.04
  - OS=Ubuntu_18.04
  - OS=CentOS_7
  - OS=Mac_OS_X

script: travis_wait 30 ./ci/test.sh
