language: bash
sudo: required

jobs:
  include:
    - stage: lint
      script: ./ci/lint.sh
    - stage: test
      env: OS=arch
      os: linux
      script: ./ci/test.sh
    - stage: test
      env: OS=manjaro
      os: linux
      script: ./ci/test.sh
    - stage: test
      env: OS=ubuntu-16.04
      os: linux
      script: ./ci/test.sh
    - stage: test
      env: OS=ubuntu-18.04
      os: linux
      script: ./ci/test.sh
    - stage: test
      env: OS=ubuntu-20.04
      os: linux
      script: ./ci/test.sh
    - stage: test
      env: OS=centos-7
      os: linux
      script: ./ci/test.sh
    - stage: test
      env: OS=centos-8
      os: linux
      script: ./ci/test.sh
    - stage: test
      env: OS=macos
      os: osx
      osx_image: xcode11.3
      script: ./ci/test.sh
